### ISSUE TITLE
Plan for a binary release on ROS 2 Dashing or Eloquent

### ISSUE THREAD

**Issue by robotpilot** [ros2/rmw_gurumdds#3]
@clemjh 
It's hard to build from source code for every Dashing version that's updated every time.
I would like to know a plan for a binary release.

**Comment by clemjh** [comment]
@robotpilot 
We are planning to release a binary package in October. Thank you.

**Comment by dirk-thomas** [comment]
@clemjh are you planning to provide binaries using the public ROS infrastructure or custom externally built binaries? If it is the former can you elaborate how CoreDDS will be made available for that?

**Comment by clemjh** [comment]
@dirk-thomas First of all, I'm sorry for late update. We've been busy for some other issues.
I'm certain that we'll release `rmw_coredds` and `rosidl_typesupport_coredds` with `bloom`, but I think that' not possible for CoreDDS. Can we add pre-built binary of CoreDDS to `packages.ros.org`? If so, how can we do that?

**Comment by dirk-thomas** [comment]
> Can we add pre-built binary of CoreDDS to packages.ros.org? If so, how can we do that?

You can provide Debian packages of CoreDDS if support for Ubuntu / Debian is what you are aiming for. Publishing them somewhere public where we can import them from (assuming the license permits that) is probably the best way to go. That will be a prerequisite before you can `bloom` the ROS packages related to CoreDDS.

The Debian package needs to be installable non-interactively. The Connext Debian package e.g. shows by default a license agreement the user has to accept but by setting an environment variable can be run unattended.

For other platforms (macOS and Windows) we currently don't offer to install the vendor packages if they are not under an open source license - simply because we have to manually maintain these machines. So for those the binary archives wouldn't contain support for CoreDDS and the user would need to build from source.

**Comment by clemjh** [comment]
Thank you for your quick response. I think we need some internal discussion about this. I'll let you know when we are ready to release the binaries. Thank you.

**Comment by wjwwood** [comment]
I'm going to close this because I believe the issue has been addressed. Feel free to continue to comment and I can reopen if necessary.

**Comment by makerj** [comment]
We are going to have a binary distribution of CoreDDS in two weeks. We had a long time to review a legal notice. Sorry for late response.

**Comment by clemjh** [comment]
Debian packages are now ready. I'm so sorry for keeping you waiting. As you might have noticed, the name 'CoreDDS' is changed to 'GurumDDS', and the repositories `rmw_coredds` and `rosidl_typesupport_coredds` is renamed to `rmw_gurumdds` and `rosidl_typesupport_gurumdds`.

**Comment by clemjh** [comment]
Debian packages are now ready. I'm so sorry for keeping you waiting. As you might have noticed, the name 'CoreDDS' is changed to 'GurumDDS', and the repositories `rmw_coredds` and `rosidl_typesupport_coredds` is renamed to `rmw_gurumdds` and `rosidl_typesupport_gurumdds`.

We created release repositories for them, [rmw_gurumdds-release](https://github.com/clemjh/rmw_gurumdds-release) and [rosidl_typesupport_gurumdds-release](https://github.com/clemjh/rosidl_typesupport_gurumdds-release) but they are not populated yet because it seemed dependency to GurumDDS need to be resolved first.

We tried to provide debian packages of GurumDDS via launchpad but we couldn't because of some issues. Can you upload them to `packages.ros.org` if we provide you the packages directly? Thank you.

**Comment by makerj** [comment]
Also, we've uploaded GurumDDS package [Here](https://static.gurum.cc/gurumdds-release/)

**Comment by makerj** [comment]
@dirk-thomas @wjwwood Can you please comment on this issue?

**Comment by dirk-thomas** [comment]
> we've uploaded GurumDDS package Here

Looking at the files provided by the Debian packages it seems their naming has a very high chance of colliding with other DDS implementation:

```
/usr/include/dds/dcps.h
/usr/include/dds/dcpsx.h
/usr/include/dds/typesupport.h
/usr/include/dds/xml.h
/usr/lib/libdds.so
```

Claiming the namespace `dds` with GurumDDS doesn't seem to be good choice. I would suggest to rename the directory containing the headers from `dds` to `gurumdds` and rename the library accordingly.

**Comment by dirk-thomas** [comment]
Btw. with Eloquent being released you probably want to create an `eloquent` branch from `master` which already targets the next distro `foxy` (in the rosidl ts and rmw repos).

**Comment by dirk-thomas** [comment]
I will yield to @tfoote if we should go ahead and import this closed source binary (after the above comments have been addressed?) or if he has any objections.

**Comment by tfoote** [comment]
The above paths are definitely an issue. Importing these packages is not impossible. However we will need to do a thorough review of the licensing, the trust chain for the import, as well as the overhead of the process.

There is one place that we've had a few examples of this is in sensor drivers. In these cases there was usually a ROS package that contained the binary artifacts. And the build step installed them into devel space and the install step installed them into the install space. 

In ROS 2 we don't need to worry about devel space and the build can be a no-op. But we definitely want to make sure that it's not doing any download/fetching during the build stage. That's another pattern that we've seen. 

However with that said, and assuming the licensing can be resolved to be valid as well as not to surprise users who don't specifically choose to use this package. A pattern where you create a ROS package that installs prebuilt binaries could relatively easily be then released via bloom. And then all our existing release and build systems could be leveraged without requiring additional pipelines or import paths. Though this would require that the installation work installed into an alternative FHS root. (aka /opt/ros/DISTRO) but the installation should also be able to drop in any necessary 

We would also want to make sure that we had coverage of the target platforms and architectures. But this is much easier if it's scoped to a specific rosdistro. And this also avoids cross distro compatibility issues mostly for a system installation which appears to be an issue similar to the include path above.

**Comment by makerj** [comment]
> Claiming the namespace dds with GurumDDS doesn't seem to be good choice. I would suggest to rename the directory containing the headers from dds to gurumdds and rename the library accordingly.

> The above paths are definitely an issue.

We've renamed both header directories and library. Updated packages(2.5.1739) are already uploaded [mentioned url](https://static.gurum.cc/gurumdds-release/).

Since it causes build failure on legacy systems, we've updated GurumDDS version from 2.4 to 2.5.

> But we definitely want to make sure that it's not doing any download/fetching during the build stage.

GurumDDS doesn't require download/fetching stage during installation.

> We would also want to make sure that we had coverage of the target platforms and architectures. But this is much easier if it's scoped to a specific rosdistro.

GurumdDDS and its RMW support Crystal and Dashing distro on Ubuntu Linux(AMD64/ARM64) and Windows(AMD64). We're planning to support Eloquent and Foxy on 2020.1.

**Comment by dirk-thomas** [comment]
@tfoote Please check the updated `.deb`s for Ubuntu 18.04 and if they can be imported in the current state.

**Comment by tfoote** [comment]
I believe that they're technically possible to import. I'm following up in a separate thread about licensing etc.
